shinh/elvm

Makefile, README.md, libc/stdio.h, target/elc.c, target/tex.c, tools/runtex.sh
Confirmed that "make tex" passes, using TeX Live 2016.
=> Add TeX backend

target/tex.c
Sorry for my previous PR. 
I fixed target/tex.c and "make tex" and "make elc-tex" works.
=> Fix bugs of TeX backend to compile elc-tex

Makefile, README.md, target/cl.c, target/elc.c
I confirmed that `make cl elc-cl` passed, using SBCL 1.3.1.debian.
=> Add Common Lisp backend

ELVM.md
Added a file ELVM.md with some more detailed description of the virtual machine than in README.md, which might be useful for anyone wanting to write a new backend. I hope it is all correct!
=> some notes on the virtual machine

Makefile, target/elc.c, target/forth.c
Use gforth to run the generated Forth program. Install gforth with:
apt-get install gforth
=> Add Forth target

Makefile, target/elc.c, target/pl.c
Is it OK to merge this as a PR? This looks pretty sane, though I wonder if some `defined xx` things are really necessary.
=> add perl script backend

Makefile, target/elc.c, target/tm.c, tools/tm.cc
Hi, this is a backend that generates Turing machines, with a TM simulator in tools/tm.cc. It's still a little bit slow and we plan to work on speeding it up, but it passes all the tests that it's been able to complete.
=> Turing machine backend

Makefile, target/elc.c, target/go.c
=> Go backend one func

Makefile, README.md, target/arm.c, target/elc.c, target/util.c, target/util.h, target/x86.c, tools/check_selfhost.sh
Basically this follows the x86 backend's approach.
`tools/check_selfhost.sh arm` passed in 160 seconds on my Raspberry Pi 3.
=> Add arm-linux backend

tools/befunge.cc
In testing I found that [beer10](https://github.com/catseye/Befunge-93/blob/master/eg/beer10.bf) isn't outputting correctly. Verified that the issue isn't a regression from this change. Will look into eventually
=> Update befunge.cc with constant propagation, fix OP_RNG

Makefile, target/elc.c, target/ps.c
I confirmed that `make ps` passed, using Ghostscript 9.15.
=> Add Postscript Backend

Makefile, target/cs.c, target/elc.c, tools/runcs.sh
It's almost the same as Java backend.
Using dotnet command https://www.microsoft.com/net/core
=> Add csharp (.NET Core) target

Makefile, target/elc.c, target/ll.c
This target is tested with LLVM 4.0.
=> Add LLVM IR target

Makefile, target.mk
=> Refactor Makefile

Makefile, target/elc.c, target/scala.c, tools/runscala.sh
I implemented Scala target.
Here is commands to confirm whether the target works or not.
```bash
./out/8cc -S -I. -Ilibc -I8cc/include -o 8cc.eir out/8cc.c
./out/elc -scala 8cc.eir > 8cc.scala
scalac -J-Xms256m -J-Xmx512m 8cc.scala
cat hello.c | scala Main
```
Then, I had ELVM IR of `hello.c`.
NOTE: `hello.c` should be prepared.
=> Add Scala target

Makefile, target/elc.c, target/hs.c, tools/runhs.sh
* Implemented Haskell target.
NOTE: Compiling `8cc.c.eir.hs` took a lot of time, but it terminated.
The following is a log of `make test-hs`. In my environment, the tests have passed
[2018-04-26-elvm-make-test-hs](https://gist.github.com/nwtgck/1c861f02e3520a4d065c542f3eb7b04c#file-2018-04-26-elvm-make-test-hs)
=> Add Haskell target

Makefile, target/elc.c, target/oct.c
I implemented Octave backend.
GNU Octave, version 3.8.1
=> Add Octave backend

README.md, tools/check_selfhost.sh, tools/rununl.sh
- Switch unlambda interpreter to https://github.com/irori/unlambda
- Add unlamba to check_selfhost.sh
=> Switch unlambda interpreter

Makefile, target/elc.c, target/rs.c, tools/runrs.sh
This pull request adds rust target. I tested this backend with rustc 1.31.0.
=> Add Rust target

Makefile, README.md, target/elc.c, target/hell.c, tools/runhell.sh
HeLL is an assembly language for Malbolge Unshackled.
Programs grow really large. Seems to pass all tests, but due to limited computing resources I couldn't run all of them.
The next steps would be more optimizations and a backend that produces Malbolge Unshackled code directly. However, I'm not sure if or when I will do these steps. Thus I do the pull request now already.
=> Add HeLL backend

Makefile, README.md, target/elc.c, target/whirl.c, tools/whirl.cc
This adds a backend for generating [Whirl](https://bigzaphod.github.io/Whirl/) programs.
=> Add whirl backend

Makefile, README.md, target/awk.c, target/elc.c
Add awk backend; this passes all tests and full tests:
make awk
make test-awk-full
Tested using GNU Awk 5.0.1 on Ubuntu 20.04.
=> Add awk backend

Makefile, README.md, target/elc.c, target/tcl.c
Add Tcl backend, passes all tests:
```
make tcl
make test-tcl-full
```
Tested using Tcl 8.6 on Ubuntu 20.04 (`apt install tcl`).
=> Add tcl backend

Makefile, README.md, target/elc.c, target/kx.c
Add Kinx backend to ELVM. [Kinx](https://github.com/Kray-G/kinx) is the scripting language as my personal project.
But Kinx has a problem with the version of 0.15.2 as currently the latest released version.
I solved the problem in the master branch and I saw it passed all tests with the latest Kinx in the master.
```
make build-kx
make test-kx
make test-kx-full
```
I am glad if you accept this.
Thanks in advance.
=> Add Kinx backend

libc/stdio.h
Fix for the `fgets` function's implementation as mentioned in #96.
=> Fix fgets implementation

libc/stdio.h, test/fgets.c
When FILE is already at EOF:
- if size<=0, ret=nullptr and buf[0] is not modified
- if size==1, ret=buf and buf[0]=0
- if size>1, ret=nullptr and buf[0] is not modified
EDIT: thanks to https://github.com/shinh/elvm/pull/99#issuecomment-778339579
=> Fix fgets implementation again

README.md
I counted the number of backends and found it was wrong.
It is a small fix.
Please check it.
Here is how to count it. Please look at the modified README.
https://github.com/Kray-G/elvm
I think this modification may not be necessary, but I added because you can check it easily.
=> fixed the wrong number of backends.

target/lol.c
also changed some lines to use UINT_MAX_STR instead of having the value inside the string literal
=> Replace bitwise 'and' custom function with modulo

Makefile, README.md, target/aheui.c, target/elc.c
[Aheui](https://esolangs.org/wiki/Aheui) is an esoteric programming language written in Hangul, the Korean alphabet.
```
make aheui
```
All tests are passed with [rpaheui 1.22-24-gb66f488](https://github.com/aheui/rpaheui/tree/b66f488).
=> Add Aheui backand
